# Generated by Django 4.2 on 2023-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ManyToManyField(to='blog.topic', verbose_name='TOPIC'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(to='blog.topic', verbose_name='TOPIC'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic',
            field=models.IntegerField(choices=[(0, 'Opinion'), (1, 'Consejo'), (2, 'Carrera'), (3, 'Clasificacion')], default=1, verbose_name='TOPIC'),
        ),
    ]
