# Generated by Django 4.2 on 2023-06-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_topic_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.topic', verbose_name='TOPIC'),
            preserve_default=False,
        ),
    ]
