# Generated by Django 4.2 on 2023-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_topic_comment_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ManyToManyField(to='blog.topic', verbose_name='TOPIC'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(to='blog.topic', verbose_name='TOPIC'),
        ),
    ]
