# Generated by Django 4.2 on 2023-06-22 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='NOMBRE')),
                ('apellido', models.CharField(max_length=50, verbose_name='APELLIDO')),
                ('telefono', models.IntegerField(max_length=50, verbose_name='TELEFONO')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('mensaje', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='MENSAJE')),
            ],
            options={
                'db_table': 'CONTACTO',
            },
        ),
    ]
