# Generated by Django 4.2 on 2023-06-19 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('estado_activo', models.BooleanField(default=1)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUARIO')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='User_rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='FECHA_CREACION')),
                ('fecha_modificacion', models.DateField(auto_now=True, null=True, verbose_name='FECHA_MODIFICACION')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rol', verbose_name='ID_ROL')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user', verbose_name='ID_USER')),
            ],
            options={
                'db_table': 'USER_ROL',
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
        migrations.DeleteModel(
            name='Persona_rol',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user', verbose_name='ID_PERSONA'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
