# Generated by Django 4.2 on 2023-06-19 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_user_user_rol_remove_persona_user_delete_persona_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('apellido', models.CharField(max_length=100, verbose_name='APELLIDO')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('contraseña', models.CharField(max_length=128, verbose_name='CONTRASEÑA')),
                ('estado_activo', models.BooleanField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUARIO')),
            ],
            options={
                'db_table': 'PERSONA',
            },
        ),
        migrations.CreateModel(
            name='Persona_rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='FECHA_CREACION')),
                ('fecha_modificacion', models.DateField(auto_now=True, null=True, verbose_name='FECHA_MODIFICACION')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persona', verbose_name='ID_PERSONA')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rol', verbose_name='ID_ROL')),
            ],
            options={
                'db_table': 'PERSONA_ROL',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.DeleteModel(
            name='User_rol',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persona', verbose_name='ID_PERSONA'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
