# Generated by Django 4.1.2 on 2023-06-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_persona_persona_rol_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(verbose_name='TELEFONO'),
        ),
    ]
