# Generated by Django 4.2 on 2023-05-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_rol_detalle_rol_detalle_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='APELLIDO'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.CharField(max_length=1000, verbose_name='MENSAJE'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='TELEFONO'),
        ),
    ]
