# Generated by Django 4.2 on 2023-05-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contacto_apellido_alter_contacto_mensaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='id_persona_rol',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'Aprobada')], default=1, max_length=20, verbose_name='ESTADO'),
        ),
    ]
