# Generated by Django 4.2 on 2023-06-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_publicacion_id_persona_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacto',
            table='home_contacto',
        ),
    ]
