# Generated by Django 4.2 on 2023-06-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contacto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacto',
            table='CONTACTO',
        ),
    ]
